kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-mysql
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi