apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: laravel5
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: laravel5
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""