apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "laravel5.fullname" . }}-nginx
  labels:
    app: {{ template "laravel5.name" . }}
    chart: {{ template "laravel5.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  nginx.conf: |-
{{ .Files.Get "nginx.conf" | indent 4 }}
  laravel-site.conf: |-
{{ .Files.Get "laravel-site.conf" | indent 4 }}
