apiVersion: v1
kind: Service
metadata:
  name: {{ template "laravel5.fullname" . }}-phpfpm
  labels:
    app: {{ template "laravel5.name" . }}-phpfpm
    chart: {{ template "laravel5.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.phpfpmService.port }}
      targetPort: {{ .Values.phpfpmService.phpfpmPort }}
      protocol: TCP
      name: phpfpm
  selector:
    app: {{ template "laravel5.name" . }}-phpfpm
    release: {{ .Release.Name }}