apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-phpfpm
  labels:
    app: {{ template "test6.name" . }}
    chart: {{ template "test6.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-phpfpm
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-phpfpm
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: fleetcore-platform-env
          secret:
            secretName: fleetcore-platform-env
#        - name: fleetcore-oauth-private
#          secret:
#            secretName: fleetcore-oauth-private
#        - name: fleetcore-oauth-public
#          secret:
#            secretName: fleetcore-oauth-public
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
      - name: {{ template "fullname" . }}-phpfpm
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
#        - name: fleetcore-oauth-private
#          mountPath: /var/www/fleetcore/storage/oauth-private.key
#          subPath: oauth-private.key
#        - name: fleetcore-oauth-public
#          mountPath: /var/www/fleetcore/storage/oauth-public.key
#          subPath: oauth-public.key
#          readOnly: false
        - name: fleetcore-platform-env
          mountPath: /var/www/fleetcore/.env
          subPath: .env
        ports:
        - containerPort: {{ .Values.phpfpmService.phpfpmPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.phpfpmService.phpfpmPort }}
          initialDelaySeconds: 10
          timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-nginx
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-nginx
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
      - name: {{ template "fullname" . }}-nginx
        image: "{{ .Values.nginxService.repository }}:{{ .Values.nginxService.imageTag }}"
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        ports:
        - name: http
          containerPort: {{ .Values.nginxService.internalPort }}
        - name: https
          containerPort: 443
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: laravel-conf
          mountPath: /etc/nginx/sites-available/
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: laravel-conf
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: laravel-site.conf
            path: laravel-site.conf
