apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "laravel5.fullname" . }}-phpfpm
  labels:
    app: {{ template "laravel5.name" . }}-phpfpm
    chart: {{ template "laravel5.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.phpfpmReplicaCount }}
  selector:
    matchLabels:
      app: {{ template "laravel5.name" . }}-phpfpm
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "laravel5.name" . }}-phpfpm
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: laravel5-env
          secret:
            secretName: laravel5-env
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-phpfpm
          image: "{{ .Values.phpfpmImage.repository }}:{{ .Values.phpfpmImage.tag }}"
          imagePullPolicy: {{ .Values.phpfpmImage.pullPolicy }}
          ports:
            - name: phpfpm
              containerPort: {{ .Values.phpfpmService.port }}
              protocol: TCP
          volumeMounts:
            - name: laravel5-env
              mountPath: /var/www/laravel5/.env
              subPath: .env
          livenessProbe:
            tcpSocket:
              port: {{ .Values.phpfpmService.port }}
            initialDelaySeconds: {{ .Values.phpfpmLivenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.phpfpmLivenessProbe.timeoutSeconds }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.phpfpmService.port }}
            initialDelaySeconds: {{ .Values.phpfpmReadinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.phpfpmReadinessProbe.timeoutSeconds }}
          resources:
{{ toYaml .Values.phpfpmResources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
