apiVersion: v1
kind: Secret
metadata:
  name: laravel5-env-seeder
  namespace: laravel5
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  .env: |-
{{ .Files.Get "laravel5-seeder-env.env" | b64enc | indent 4 }}