# the number of replicas for the nginx service
nginxReplicaCount: 1
# the number of replicas for the phpfpm service
phpfpmReplicaCount: 3

#Uncomment to add your image pull secret which has access to both PHP and nginx repositories
#imagePullSecrets: my-secret-name

# Set this to true to run an initial dumping and seeding of database on initial helm install. This does not seed on upgrades.
preInstallJob: true
preInstallCommand:
  # Start artisan in backgrounde mode, then dump database and seed.
  # The .env for the pre-install job is different because it needs to seed local files without SSL.
  # The APP_ENV is set to APP_ENV=seeder and the APP_URL is set to: APP_URL=http://localhost:8000
  # which aren't yet available over https at desired url.
  # If you change the below commands, please double check the [args] command in kubernetes/helm/laravel5/templates/deployment-phpfpm.yaml still works
  # Also check that the entrypoint.sh logic still works: docker/php-fpm/entrypoint.sh
  first: "php /var/www/laravel5/artisan serve &"
  second: "php /var/www/laravel5/artisan migrate:fresh --force --seed"

# Set this to true to run an migrations before every upgrade
preUpgradeJob: true
preUpgradeCommand:
  # Preform migrations. If you change the below commands, please double check the [args] command in kubernetes/helm/laravel5/templates/deployment-phpfpm.yaml still works
  # Also check that the entrypoint.sh logic still works: docker/php-fpm/entrypoint.sh
  first: "php artisan migrate --force"

# The nginx image repository details
nginxImage:
  repository: quay.io/eamonkeane/laravel-nginx
  tag: latest
  pullPolicy: Always

# The nginx readiness and liveness values
nginxLivenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 5
nginxReadinessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 5

# The phpfpm image repository details
phpfpmImage:
  repository: quay.io/eamonkeane/laravel
  tag: latest
  pullPolicy: Always

# The phpfpm readiness and liveness values
phpfpmLivenessProbe:
  initialDelaySeconds: 40
  timeoutSeconds: 5
phpfpmReadinessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 5

# The nginx service values
nginxService:
  type: ClusterIP
  externalPort: 80
  internalPort: 80

# The phpfpm service values
phpfpmService:
  type: ClusterIP
  port: 9000

# Ingress details
ingress:
  enabled: true
  annotations:
  # This tells the nginx-ingress controller to create an ingress. If you use Google, Amazon's or Azure's change accordingly
     kubernetes.io/ingress.class: nginx
  # This tells the cert-manager cluster-issuer resource to create a certificate for this ingress
     kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - laravel2.squareroute.io
   # If enabling ssl please keep in mind the following:
   # The default laravel 5.5 demo project served mixed content (attempting to serve static assets over http), so the following block of code was added to api.php and web.php:
   # if (App::environment('production')) {
   #    URL::forceScheme('https');
   #}
   # https://laracasts.com/discuss/channels/laravel/mixed-content-issue-content-must-be-served-as-https?page=2
   # If you are looking to use SSL for other environments (such as staging) please modify api.php and web.php to forceScheme for those environments
  tls:
    - secretName: laravel2.squareroute.io
      hosts:
        - laravel2.squareroute.io

nginxResources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

phpfpmResources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
